
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Loading necessary packages. 

library(ggrepel)
library(janitor)
library(tidytext)
library(tidyverse)
```

```{r, include = FALSE}

# Reading in the data and cleaning it. Only using Trump speeches and then
# counting words.

trump_speeches <- read_csv("raw-data/speeches_new.csv") %>% 
  select("Speaker":"Text") %>% 
  clean_names() %>% 
  filter(speaker == "Donald Trump") %>% 
  group_by(title) %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  count(word, sort = TRUE)
  
# Counting words by each differnet content category

populism <- trump_speeches %>% 
  group_by(title) %>% 
  filter(str_detect(word, "deceit") | str_detect(word, "treason")
         | str_detect(word, "betray") | str_detect(word, "absurd")
         | str_detect(word, "arrogant") | str_detect(word, "promise") 
         | str_detect(word, "corrupt") | str_detect(word, "direct")
         | str_detect(word, "elite") | str_detect(word, "establishment")
         | str_detect(word, "ruling") | str_detect(word, "caste")
         | str_detect(word, "class") | str_detect(word, "mafia")
         | str_detect(word, "freedom of expression")
         | str_detect(word, "undemocratic") | str_detect(word, "politic")
         | str_detect(word, "propaganda") | str_detect(word, "referend")
         | str_detect(word, "regime") | str_detect(word, "shame")
         | str_detect(word, "admit") | str_detect(word, "tradition")
         | str_detect(word, "people")) %>% 
  mutate(populism_count = sum(n)) %>% 
  arrange(desc(populism_count))

environment <- trump_speeches %>% 
  group_by(title) %>% 
  filter(str_detect(word, "green") | str_detect(word, "climate")
         | str_detect(word, "environment") | word == "heating") %>% 
  mutate(environment_count = sum(n)) %>% 
  arrange(desc(environment_count))

immigration <- trump_speeches %>% 
  group_by(title) %>% 
  filter(str_detect(word, "asylum") | str_detect(word, "halal")
         | str_detect(word, "scarf") | str_detect(word, "illegal")
         | str_detect(word, "immigra") | str_detect(word, "ISlam") 
         | str_detect(word, "Koran") | str_detect(word, "Muslim")
         | str_detect(word, "foreign")) %>% 
  mutate(immigration_count = sum(n)) %>% 
  arrange(desc(immigration_count))

progressive <- trump_speeches %>% 
  group_by(title) %>% 
  filter(word == "progressive" | word == "right" | word == "freedom" 
         | word == "self-disposition" | word == "handicap" | word == "poverty" 
         | word == "protection" | word == "honest" | word == "equal" 
         | word == "education" | word == "pension" | word == "social" 
         | word == "weak") %>% 
  mutate(progressive_count = sum(n)) %>% 
  arrange(desc(progressive_count))

conservatism <- trump_speeches %>% 
  group_by(title) %>% 
  filter(word == "belief" | word == "family" | word == "church"
         | word == "norm" | word == "porn" | word == "sex" | word == "values"
         | word == "conservative" | word == "conservatism") %>% 
  mutate(conservatism_count = sum(n)) %>% 
  arrange(desc(conservatism_count))

sentiment_trump_speeches <- populism %>% 
  full_join(environment, by = "title") %>% 
  full_join(immigration, by = "title") %>% 
  full_join(progressive, by = "title") %>% 
  full_join(conservatism, by = "title") %>% 
  select(title, populism_count, environment_count, immigration_count, 
         progressive_count, conservatism_count) %>% 
  distinct()

```

```{r, include = FALSE}

# Setting nas to 0

sentiment_trump_speeches[is.na(sentiment_trump_speeches)] = 0

# Making a plot with the extreme values having a specific color

plot <- ggplot(sentiment_trump_speeches, aes(populism_count,
                                             immigration_count)) +
  geom_point(
    color = case_when(sentiment_trump_speeches$populism_count > 55 ~ "#1b9e77",
                      sentiment_trump_speeches$immigration_count > 25
                      ~ "#d95f02", TRUE ~ "#7570b3"))

# Adding geom labels with repel to the extreme populism speeches.

plot2 <- plot +
  geom_label_repel(aes(label = ifelse(populism_count > 55, as.character(title),
                                      '')),
                  size = 3,
                  box.padding   = 0.35, 
                  point.padding = 0.4,
                  segment.color = 'grey50') +
  labs(title = "Content Analysis of Trump's Speechs",
       subtitle = "30 speeches and interviews from the 2016 campaign",
       x = "Count of Populist Language", y = "Count of Language Relating to
       Immigration") +
  theme_classic()
  
# Adding labels to the extreme immigration count speeches

plot3 <- plot2 +
  geom_label_repel(aes(label = ifelse(immigration_count > 25,
                                      as.character(title), '')),
                  size = 2.6,
                  box.padding   = 0.3, 
                  point.padding = 0.1,
                  segment.color = 'grey50')
```

```{r, include = FALSE}

plot3

# Saving my plot to the shiny app directory.

ggsave("speeches_shiny/dist_plot.png")
```



